package de.hetzge.eclipse.aicoder;

public enum AiCoderImageKey {
	PACKAGE_ICON,
	TYPE_ICON,
	ENUM_ICON,
	INTERFACE_ICON,
	RECORD_ICON,
	ANNOTATION_ICON,
	RESOURCE_ICON,
	SCOPE_ICON,
	COPY_ICON,
	BEFORE_ICON,
	AFTER_ICON,
	PIN_ICON,
	IMPORT_ICON,
	BLACKLIST_ICON,
	FILL_IN_MIDDLE_ICON,
	INFORMATIONS_ICON,
	DEPENDENCIES_ICON,
	EDITOR_ICON
}
